name: CI Pipeline

on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bash Test Script
        # بنقول للـ Runner يدخل جوه الفولدر اللي فيه ملف التيست
        working-directory: ./src
        run: bash test.sh