name: CI Pipeline

on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test
        # السطر اللي تحت ده هيخلي الأأمر يتنفذ جوه فولدر src بالظبط
        working-directory: ./src
        run: npm start